### ISSUE TITLE
the softwear work properly but has some worning 

### ISSUE THREAD

**Issue by MTalafha82** [3fon3fonov/exostriker-manual#2]
which: no urxvt2 in (/usr/lib64/ccache:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/home/talafha/makee/bin:/home/talafha/makee/bin)
![WhatsApp Image 2023-06-10 at 03 00 20](https://github.com/3fon3fonov/exostriker-manual/assets/134651099/1ad08a5f-794e-409b-bfde-e4bae6cfd5ca)
![WhatsApp Image 2023-06-10 at 03 00 20](https://github.com/3fon3fonov/exostriker-manual/assets/134651099/3eb8e47f-9756-4301-834b-b1a529e6629d)
the graphic face of the softwear is not normal - please ,find attached file

**Comment by 3fon3fonov** [comment]
Ah, this is an old issue, which I just discovered. Always write here: https://github.com/3fon3fonov/exostriker/issues

Generally, your screen resolution is poor. Else, try to reduce the GUI font form the "settings" action menu. That should be permanent setup. Anyway, upgrade to Version 0.88 as of June 2024.
